<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="axis_dome_fixed" params="prefix parent stand_height:=0.062 *origin">
    <link name="${prefix}_base_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://axis_description/meshes/axis_dome.stl" scale="1 1 1" />
        </geometry>
        <material name="axis_white">
          <color rgba="0.8 0.8 0.8 1.0" />
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <!-- Cylinder for the main body of the camera -->
        <geometry>
          <cylinder radius="0.09" length="0.09" />
        </geometry>
        <origin xyz="0 0 ${stand_height + 0.09/2}" rpy="0 0 0" />
      </collision>
      <collision>
        <!-- Sphere collider for the dome itself -->
        <geometry>
          <sphere radius="0.067" />
        </geometry>
        <origin xyz="0 0 ${stand_height + 0.09}" />
      </collision>
      <collision>
        <!-- Box collider for the metal stand the camera sits on -->
        <geometry>
          <box size="0.04 0.08 ${stand_height}" />
        </geometry>
        <origin xyz="0 0 ${stand_height/2}" rpy="0 0 0" />
      </collision>
    </link>
    <joint name="${prefix}_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}_base_link" />
    </joint>

    <link name="${prefix}_link" />
    <joint name="${prefix}_camera_joint" type="fixed">
      <parent link="${prefix}_base_link" />
      <child link="${prefix}_link" />
      <origin xyz="0.047 0 ${stand_height + 0.09 + 0.047}" rpy="0 0.7854 0" />
    </joint>

    <!--
      Simulation support: sensor plugin
    -->
    <gazebo reference="${prefix}_link">
      <plugin filename="libgz-sim-sensors-system.so" name="gz::sim::systems::Sensors">
        <render_engine>ogre2</render_engine>
      </plugin>

      <sensor name="${prefix}_camera" type="camera">
        <update_rate>15</update_rate>
        <visualize>true</visualize>
        <always_on>true</always_on>
        <gz_frame_id>${prefix}_link</gz_frame_id>
        <topic>$(arg namespace)/sensors/${prefix}/image</topic>
        <camera>
          <horizontal_fov>1.5184351666666667</horizontal_fov>
          <vertical_fov>1.0122901111111111</vertical_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
        </camera>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
