<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      mounts.urdf.xacro
\authors   Luis Camero <lcamero@clearpathrobotics.com>
\copyright Copyright (c) 2022, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!--
        Full Riser: add plate sized riser
        - within PACS grid framework, only input required is 'level' (height)
        - adds legs and mounts
    -->
  <xacro:macro name="riser" params="name parent_link thickness:=0.00635 rows:=8 columns:=7 *origin">
    <xacro:property name="spacing" value="0.08" />
    <xacro:property name="parent_coordinate" value="${parent_link[-2:]}"/>
    <xacro:property name="standard_size" value="False"/>
    <!-- Partial Riser Plate Link -->
    <link name="${name}_link">
      <visual>
        <geometry>
          <xacro:if value="${rows == 8 and columns == 7}">
            <xacro:property name="standard_size" value="True"/>
            <xacro:property name="thickness" value="0.00635"/>
            <mesh filename="package://clearpath_mounts_description/meshes/pacs/riser_8x7.stl" />
          </xacro:if>
          <xacro:if value="${rows == 1 and columns == 7}">
            <xacro:property name="standard_size" value="True"/>
            <xacro:property name="thickness" value="0.00635"/>
            <mesh filename="package://clearpath_mounts_description/meshes/pacs/riser_1x7.stl" />
          </xacro:if>
          <xacro:unless value="${standard_size}">
            <box size="${rows * spacing} ${columns * spacing} ${thickness}"/>
          </xacro:unless>
        </geometry>
        <material name="clearpath_dark_grey" />
        <origin xyz="${-(rows / 2) * spacing + spacing / 2} ${-(columns / 2) * spacing + spacing / 2} ${thickness / 2}" rpy="0 0 0" />
      </visual>
      <collision>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0" />
        <geometry>
          <box size="0.11 0.59 ${thickness}" />
        </geometry>
        <material name="clearpath_dark_grey" />
      </collision>
    </link>
    <!-- Row Riser Plate Joint -->
    <joint name="${name}_joint" type="fixed">
      <child link="${name}_link" />
      <parent link="${parent_link}" />
      <xacro:insert_block name="origin" />
    </joint>
    <!-- Row Riser Mounts -->
    <xacro:full_mounts name="${name}" parent_link="${name}_link" column="${parent_coordinate[0]}" row="${parent_coordinate[1]}" columns="${columns}" rows="${rows}" z="${thickness}" />
  </xacro:macro>
</robot>
