controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ${name}_controller:
      type: position_controllers/GripperActionController

${name}_controller:
  ros__parameters:
    default: true
    joint: ${name}_right_finger_bottom_joint
    allow_stalling: true
