# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ${controller_name}_joint_trajectory_controller

  ${controller_name}_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ${name}_joint_1
      - ${name}_joint_2
      - ${name}_joint_3
      - ${name}_joint_4
      - ${name}_joint_5
      - ${name}_joint_6
