controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ${name}_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

${name}_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ${name}_shoulder_pan_joint
      - ${name}_shoulder_lift_joint
      - ${name}_elbow_joint
      - ${name}_wrist_1_joint
      - ${name}_wrist_2_joint
      - ${name}_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
